---
- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages
  apt:
    state: latest
    update_cache: yes
    name: 
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - python3-setuptools

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update apt and ensure docker-ce is installed
  apt:
    update_cache: yes
    name: "{{ docker_package }}"
    state: present

# - name: Install docker-compose
#   apt:
#     name: docker-compose
#     state: present
#   when: "install_compose == true"

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_group_members }}"
  #loop: "{{ lookup('dict', docker_group_members, wantlist=True) }}"
  when: docker_group_members | length>0