---
- include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: Darwin.yml
  when: ansible_os_family == 'Darwin'

# Required for Ansible to perform docker tasks like run containers
- name: Install Docker SDK for Python
  pip:
    name:
      - setuptools_rust
      - docker
      - docker-compose
    executable: "{{ docker_pip_executable }}"
