---
- include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: darwin_docker.yml
  when: ansible_os_family == 'Darwin' and docker_desktop_osx == 'docker'

- include_tasks: darwin_colima.yml
  when: ansible_os_family == 'Darwin' and docker_desktop_osx == 'colima'

# Required for Ansible to perform docker tasks like run containers
- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name:
      - setuptools_rust
      - docker
      - docker-compose
    executable: "{{ docker_pip_executable }}"
