---
- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: Darwin.yml
  when: ansible_os_family == 'Darwin'

# Required for Ansible to perform docker tasks like run containers
- name: Install Docker SDK for Python
  pip:
    name:
      - seutptools_rust
      - docker
      - docker-compose
    executable: "{{ docker_pip_executable }}"
