name: Ansible CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  VER_ANSIBLE: '5.2.0'
  VER_ANSIBLE_LINT: '5.3.2'
  VER_MOLECULE_VERSION: '5.3.2'

jobs:
  default:
    uses: Diehlabs/shared-workflows/.github/workflows/ansible-ci.yml@develop
    with:
      ansible_version: ${ {env.VER_ANSIBLE }}
      ansible_lint_version: ${{ env.VER_ANSIBLE_LINT }}
      molecule_version: ${{ env.VER_MOLECULE_VERSION }}

  all_vars:
    uses: Diehlabs/shared-workflows/.github/workflows/ansible-ci.yml@develop
    with:
      scenario: more_vars
      ansible_version: ${ {env.VER_ANSIBLE }}
      ansible_lint_version: ${{ env.VER_ANSIBLE_LINT }}
      molecule_version: ${{ env.VER_MOLECULE_VERSION }}
