name: Ansible CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  default:
    uses: Diehlabs/shared-workflows/.github/workflows/ansible-ci.yml@develop
    with:
      ansible_version: '5.2.0'
      ansible_lint_version: '5.3.2'
      molecule_version: '3.5.2'

  all_vars:
    uses: Diehlabs/shared-workflows/.github/workflows/ansible-ci.yml@develop
    with:
      scenario: more_vars
      ansible_version: '5.2.0'
      ansible_lint_version: '5.3.2'
      molecule_version: '3.5.2'
