name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  call-workflow:
    uses: YOUR_ORG/devops-templates/.github/workflows/ansible-standard.yml@main
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
